### ISSUE TITLE
Installing app for non-Rust users

### ISSUE THREAD

**Issue by tatthien** [huytd/ascii-d#23]
Hi, is there a pre-build package for non-Rust users?

I want to install this app but don't want to install `Rust/Cargo`.

**Comment by huytd** [comment]
I have added a github action to create the prebuilt binary.

You can download the binary for v0.3.0 here https://github.com/huytd/ascii-d/releases/tag/v0.3.0

It's a non-signed and non-notarized build btw, so on the first time running, macOS might say something about delete the app, we can just ignore and open the app by right click on it and select open.

In the future, the app will be published to AppStore, as well as having a notarized build available for direct download.

**Comment by tatthien** [comment]
Awesome! I really appreciate your effort to create the binary so quickly.
